### ISSUE TITLE
assetylene doesn't work on MT-6.2

### ISSUE THREAD

**Issue by cmatsuo** [endevver/mt-plugin-assetylene#2]
Hi Jay. This is Chieko from SAKK, a QA of MT.

We updated asset upload feature at MT-6.2 and assetylene doesn't work on the latest version anymore.
We got feedback from an user who had to rollback to 6.1.2 because of this plugin. 

Any chance you gonna  update this plugin?

Cheers.
Chieko

**Comment by jayallen** [comment]
Hi Chieko.  Assetylene was created by Brad Choate but I assume he's not maintaining it anymore.  So, yes, we very likely will since we have clients who use it.

**Comment by jayallen** [comment]
...though our customer is still on 6.1.2 and isn't upgrading for a few months.  That said, we'll try to test it out with 6.2 ASAP and see if we can reproduce the problem.  Do you happen to have steps to reproduce or is it really obvious?

**Comment by cmatsuo** [comment]
It's obvious. You don't see "Insert a caption?" on File Options when you insert an image for an entry.

**Comment by danwolfgang** [comment]
Hey Cheiko -- I'm a little confused -- isn't this exactly what the new EnableUploadCompat config directive is for?

**Comment by cmatsuo** [comment]
Yeah, it's kind of, Dan. EnableUploadCompat can make you use old upload feature instead of new one. You can't upload multiple files or drag and drop with old one though. 
New one have same old File Options screen but  assetylene doesn't work.

**Comment by danwolfgang** [comment]
I believe release 2.0.0 should remedy the compatibility problems.
https://github.com/endevver/mt-plugin-assetylene/releases

**Comment by kimonostereo** [comment]
I gave the new version a shot using the example template code just to see if it worked. I uploaded an image, then added a caption, after clicking Finish, the Movable type screen just froze. Checking the server, it seems like Perl started taking over the processes at 100%. I let it run for a bit. Then MT image asset insertion screen went blank. 

I got out of that screen and can see that it created a thumbnail, but couldn’t get past that point to add it.

I tried uploading an image and unchecking thumbnail and had the same issue: Perl running at 100% processor and a frozen MT image asset insertion screen.

I’m on MT 6.2.2
Perl 5.12
Image::Magick

Let me know if you need any other configuration settings that I'm using.

**Comment by danwolfgang** [comment]
Hey Scott -- I made an update to fix a bug where no Asset Insertion template caused trouble (version 2.0.1) but I'm not sure it'll help you. If not, you can create a new Issue for your problem.
