### ISSUE TITLE
MT6.2.2: Perl Takes Over Server and Freezing Browser Screen

### ISSUE THREAD

**Issue by kimonostereo** [endevver/mt-plugin-assetylene#3]
Hi Dan,

I gave the updated version (2.0.1) another shot and had the same issues. Perl 5.12 took over my server and it even killed Safari on my Mac. I had to force quit to get Safari to respond.

Steps:
- Added Assetylene to plugins folder on server.
- Went into blog. Checked that Template Module had Assetylene sample code from Github installed.
- Uploaded a photo using drag and drop. Image uploads successfully.
- Clicked Insert
- Insert Options screen had the following checked: Display Image in entry/page, Use thumbnail (width 350px), Alignment: center, Use caption. Added a caption.
- Clicked Finish

Results:
For about 30-45 seconds nothing but a frozen screen. Then the screen went white for about 20 seconds. Then the image finally appeared in the entry. When trying to view the html code (clicking the "< >" button) Safari browser had a long delay, then showed the image but the entire editing bar was below the body window. Safari then "beachballed" and froze.

Checked the server and saw that Perl had multiple processes running at 80-100%.

Killed the Perl processes and tried to access the entry with the image I just uploaded. Attempting to open the entry caused Perl processes to spin up again. Tried multiple attempts to open the entry but Movable Type wouldn't open it. Deleting the post and removing Assetylene returned the server to normal.

I tried this with Chrome and had similar results. Chrome requested to kill the browser page instead of freezing the entire browser.

I also did a screen capture if you'd like to see a movie of this happening.

**Comment by danwolfgang** [comment]
Hey Scott -- how many assets do you have in the system? I wonder if you're seeing the bug I just fixed in 2.0.2, which would try to insert all images regardless of your selection.

**Comment by kimonostereo** [comment]
Hi Dan,
The issue with Perl taking over the server was fixed, but now I can't get any caption to appear.

Using the sample code:

```
<div class="assets">
<mt:Assets><mt:Section strip_linefeeds="1" replace="    ","">
    <mt:If tag="AssetyleneCaption">
        <div class="caption align-<mt:AssetyleneAlign>">
        <mt:If tag="AssetyleneThumb">
            <mt:AssetyleneThumbWidth setvar="thumb_width">
            <img src="<mt:AssetThumbnailURL width="$thumb_width">" alt="<mt:AssetLabel>" />
        <mt:Else>
            <img src="<mt:AssetURL>" alt="<mt:AssetLabel>" />
        </mt:If>
            <div><mt:AssetyleneCaption></div>
        </div>
    <mt:Else>
        <mt:AssetyleneDefaultHTML>
    </mt:If>
</mt:Section>
</mt:Assets></div>
```

I get this as a resulting html:
`<div class="assets"><a href="http://www...com/uploads/IMG_0007.jpg"><img alt="IMG_0007.jpg" src="http://www....com/assets_c/2016/02/IMG_0007-thumb-350xauto-65889.jpg" width="350" height="263" class="mt-image-center" style="text-align: center; display: block; margin: 0 auto 20px;" /></a></div>`

Not sure how to fix this one. I took a look at Tags.pm and noticed that line 38 says 'caption' instead of 'include'. I tried modifying that, but it didn't do anything to add the caption to the resulting html.

**Comment by kimonostereo** [comment]
Hi Dan- Just wanted to let you know that I downloaded 2.0.3 a few days ago and got it working on my install! Thanks for the fix! I used `<mt:If tag="mt:AssetType" eq="image">` to specify if the asset is an image or a document since there was no way for the plugin to determine that.

**Comment by danwolfgang** [comment]
Great to hear 2.0.3 works!

You're doing things "correctly" by using the AssetType tag; the Asset context is available specifically to allow you to do this sort of thing.
